config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :students do 
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of :description, :street, :city, :state, :zip_code
  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name
  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

 def create
    @address = Address.new(address_params)
    @address.student_id = params[:student_id]
    @address.save
    redirect_to student_path(@address.student)
  end

  private

  def address_params
    params.require(:address).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
    @address = Address.new
    @address.student_id = @student.id
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    if @student.save
      flash[:success] = "#{@student.name} updated!"
      redirect_to student_path(@student)
    else
      render :edit
    end
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success] = "#{@student.name} added!"
      redirect_to student_path(@student)
    else
      render :new
    end
  end

   def destroy
    @student = Student.find(params[:id])
    @student.destroy
    flash[:success] = "#{@student.name} was successfully deleted!"
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<%= form_for [@student, @address] do |f| %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :street %>
  <%= f.text_field :street %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip_code %>
  <%= f.number_field :zip_code %>

  <%= f.submit %>

<% end %>

app/views/addresses/new.html.erb
<h2>Create A New Address</h2>
<p><%= link_to "See All Students", students_path%></p>
<p><%= link_to "Create New Student", new_student_path%></p>
<%= render partial: "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enrollment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h3>Edit Student: <%=@student.name%> </h3>
<p><%= link_to "See All Students", students_path%></p>
<p><%= link_to "Create New Student", new_student_path%></p>

<%= render partial: "form" %>

app/views/students/index.html.erb
<h1>All Students</h1>

  <% @students.each do |student| %>
  <%=  link_to "#{student.name}", student_path(student) %>
  <%= link_to "Delete", student_path(student), method: "delete" %>
  <% end %>

<p><%= link_to "See All Students", students_path%></p>
<p><%= link_to "Create New Student", new_student_path%></p>

app/views/students/new.html.erb
<h2>Create A New Student</h2>
<p><%= link_to "See All Students", students_path%></p>
<p><%= link_to "Create New Student", new_student_path%></p>
<%= render partial: "form" %>

app/views/students/show.html.erb
<h1>Student</h1>
<h3><%=@student.name%></h3>

<h4> Addresses for <%=@student.name%> </h4>
<%@student.addresses.each do |address|%>
  <%= address.description %>
  <%= address.street %>
  <%= address.city %>
  <%= address.state %>
  <%= address.zip_code %>
<% end %>

<p><%= link_to "See All Students", students_path%></p>
<p><%= link_to "Create New Student", new_student_path%></p>